In [1]:
import os 
import math
import random
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm
from numpy import count_nonzero

dir_ = '../data/'
group_dir_ = '../data/groups/low'

In [2]:
file_name = 'normalized_to_rating_filter_track_5_user_100.csv'
svd = pd.read_pickle(os.path.join(dir_, 'prediction_svd_top_N_' + file_name[:-3] + 'pkl'))
test = pd.read_pickle(os.path.join(dir_, 'test_' + file_name[:-3] + 'pkl'))
test.sort_values(by=['uid','tid'])

file_name = 'normalized_popularity_filter_track_5_user_100.pkl'
pop_count = pd.read_pickle(os.path.join(dir_, file_name))

num_user = len(svd['uid'].unique())
num_user

220

In [3]:
groups_n =[]
group_sizes = ['2', '3', '4', '5', '6', '7', '8']
for i in range(len(group_sizes)):
    groups = np.loadtxt(os.path.join(group_dir_, group_sizes[i] + '.csv'), delimiter=',')
    groups_n.append(groups)

In [4]:
for i in groups_n:
    print(len(i[0]))

2
3
4
5
6
7
8

In [5]:
svd['count'] = 1
svd[:5]

   uid  tid    rating  count
0    0    3  2.544071      1
1    0    7  2.545822      1
2    0   18  2.152490      1
3    0   20  1.882396      1
4    0   31  2.410806      1

In [6]:
pop_count = pop_count.sort_values(by=['count'],  ascending=False)
pop_count[:10]

         tid  count  rating
166      166   3666  573.25
457      457   2042  162.00
6338    6338   1896  153.75
80        80   1835  412.25
1364    1364   1792  327.50
350      350   1667  359.75
7209    7209   1454  400.50
6282    6282   1397   17.75
13104  13104   1368   57.50
3761    3761   1340  354.50

In [7]:
# Linear
# size = int(len(pop_rating) // 5)
# pop_normalized = pd.DataFrame()
# for i in range(5):
#     if i == 0:
#         pop = pop_count[:size].copy()
#     elif i == 4:
#         pop = pop_count[size*4:].copy()
#     else:
#         pop = pop_count[size*i:size*(i+1)].copy()
#     pop['rating'] = (5 - i)
#     pop_normalized = pop_normalized.append(pop)
# pop_normalized = pop_normalized[['tid', 'rating']]

In [8]:
# min_max
max_rating = pop_count.iloc[0]['count']
pop_normalized = pop_count.copy()
pop_normalized = pop_normalized[['tid', 'count']]
pop_normalized['rating'] = pop_normalized['count']
pop_normalized['rating'] /= max_rating
pop_normalized['rating'] *= 5
pop_normalized[:10]

         tid  count    rating
166      166   3666  5.000000
457      457   2042  2.785052
6338    6338   1896  2.585925
80        80   1835  2.502728
1364    1364   1792  2.444081
350      350   1667  2.273595
7209    7209   1454  1.983088
6282    6282   1397  1.905346
13104  13104   1368  1.865794
3761    3761   1340  1.827605

In [9]:
lambdas = []
for i in range(11):
    lambdas.append(i/10)
lambdas

[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

In [14]:
for lambda_ in tqdm(lambdas):
    top_n_size = 50
    top_n_lists_g = []
    for groups in groups_n:

        group_size = len(groups[0])
        top_n_lists = []

        for group in groups:
            rating_table = pd.DataFrame() 
            for member in group:
                prediction = svd[svd['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = prediction
                else:
                    rating_table = rating_table.set_index('tid').add(prediction.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= group_size 
            rating_table['rating'] *= lambda_
            pop = pop_normalized.copy()
            pop['rating'] *= (1 - lambda_)
            rating_table = rating_table.set_index('tid').add(pop.set_index('tid'), fill_value=0).reset_index()
    #         rating_table = rating_table[rating_table['count'] == group_size]
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            rating_table = rating_table[:top_n_size]
            top_n_list = []
            for _, row in rating_table.iterrows():
                top_n_list.append(row[0])
            top_n_lists.append(top_n_list)
        top_n_lists_g.append(top_n_lists)   
        
#     print('lambda = ' + str(lambda_))
    threshold = 0.0
    avg_precisions = []
    avg_recalls = []
    for i in range(len(groups_n)):
        groups = groups_n[i]
        top_n_lists = top_n_lists_g[i]

        precisions = []
        recalls = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]
            
            for k in range(len(group)):
                high_rating = 0
                for l in range(top_n_size):
                    uid = group[k]
                    tid = top_n_list[l]
                    t = test[test['uid'] == uid]
                    t = t[t['tid'] == tid]
                    if len(t) > 0 and t.iloc[0]['rating'] > threshold:
                        high_rating += 1

                precision = high_rating / top_n_size
                recall = high_rating / len(test[test['uid'] == uid])
                precisions.append(precision)
                recalls.append(recall)
            

        avg_precision = 0
        for precision in precisions:
            avg_precision += precision
        avg_precision /= len(precisions)
        avg_precisions.append(avg_precision)

        avg_recall = 0
        for recall in recalls:
            avg_recall += recall
        avg_recall /= len(recalls)
        avg_recalls.append(avg_recall)
        
    print(avg_precisions)
    print(avg_recalls)
    print('----------------------------------------') 
#     print(sum(avg_precisions) / len(avg_precisions))
#     print('----------------------------------------')

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=11.0), HTML(value='')))

[0.06253333333333323, 0.046060606060606045, 0.03710526315789476, 0.0390769230769231, 0.034666666666666686, 0.03392857142857145, 0.032857142857142876]
[0.009587652868100868, 0.010194397980992849, 0.010778118185785328, 0.011648637760647722, 0.011451714784235794, 0.011263944589279068, 0.011931615453516004]
----------------------------------------
[0.07239999999999988, 0.052121212121212096, 0.04026315789473687, 0.040615384615384637, 0.03600000000000002, 0.03535714285714288, 0.03250000000000002]
[0.010695855763565468, 0.010756589068904915, 0.01140499052946921, 0.012175561224979457, 0.01188880911302678, 0.011563458678546846, 0.011652689421918123]
----------------------------------------
[0.08133333333333319, 0.05474747474747469, 0.042368421052631604, 0.039692307692307714, 0.03500000000000002, 0.03571428571428573, 0.032857142857142876]
[0.011151250429530364, 0.011264199512980041, 0.011803594050903688, 0.011762590683108186, 0.011637085688055002, 0.01162338685945081, 0.011665345600724552]
----------------------------------------
[0.08893333333333318, 0.05858585858585852, 0.044736842105263186, 0.0390769230769231, 0.03633333333333335, 0.03607142857142859, 0.03357142857142859]
[0.011118095041926268, 0.01153244079169349, 0.011889180907059463, 0.011511423066736474, 0.011720322134908406, 0.011429446255612218, 0.011893146914190975]
----------------------------------------
[0.09986666666666652, 0.06242424242424235, 0.0510526315789474, 0.04030769230769233, 0.03866666666666669, 0.03750000000000002, 0.03321428571428573]
[0.012025405129298691, 0.011648150052870055, 0.012891906700245287, 0.011757667522463542, 0.012438938331419038, 0.011554102401741349, 0.011699516613388793]
----------------------------------------
[0.10453333333333316, 0.06686868686868679, 0.053157894736842126, 0.042769230769230795, 0.043666666666666694, 0.03821428571428572, 0.03321428571428573]
[0.012071545276741586, 0.011342445177725756, 0.012510264335162821, 0.012718672238193708, 0.013145832305849219, 0.011657711702064326, 0.01117949277377713]
----------------------------------------
[0.11293333333333312, 0.07050505050505042, 0.058684210526315804, 0.04492307692307695, 0.045666666666666696, 0.04035714285714287, 0.031071428571428587]
[0.012574122175204547, 0.011659996171382334, 0.012858959904717191, 0.013350920131036465, 0.014751420676298869, 0.0124652959487505, 0.009874874538414142]
----------------------------------------
[0.11346666666666648, 0.07111111111111103, 0.06052631578947367, 0.048615384615384644, 0.048666666666666684, 0.041071428571428585, 0.032142857142857154]
[0.012037069545175291, 0.01110957446011483, 0.012454902991162564, 0.014258889039073333, 0.014976257136086303, 0.011463381704595668, 0.009615796443968786]
----------------------------------------
[0.11146666666666645, 0.0705050505050504, 0.058157894736842096, 0.04584615384615387, 0.04733333333333335, 0.04250000000000002, 0.033571428571428585]
[0.012045020633000851, 0.010668503859305447, 0.011645869384824191, 0.011835212901364562, 0.014622920822406078, 0.011454912810068907, 0.00979982328596515]
----------------------------------------
[0.09773333333333317, 0.06343434343434338, 0.052105263157894766, 0.04246153846153848, 0.04700000000000003, 0.036785714285714304, 0.03250000000000001]
[0.010277528569388695, 0.009125283936442482, 0.01010029527314418, 0.010625565004381556, 0.013161841854338947, 0.00949302373027963, 0.009056396971501474]
----------------------------------------
[0.08013333333333321, 0.04989898989898983, 0.04184210526315791, 0.0313846153846154, 0.032333333333333346, 0.024642857142857154, 0.025714285714285724]
[0.008094795344863525, 0.006914705778117767, 0.007792415463034717, 0.007325397597105747, 0.00784325232912776, 0.0066790973362088986, 0.0063140250760733985]
----------------------------------------

In [10]:
def dcg_at_k(r, k, method=0):
    r = np.asfarray(r)[:k]
    for i in range(len(r)):
        r[i] = 2**r[i] -1
    
    if r.size:
        if method == 0:
            return r[0] + np.sum(r[1:] / np.log2(np.arange(2, r.size + 1)))
        elif method == 1:
            return np.sum(r / np.log2(np.arange(2, r.size + 2)))
        else:
            raise ValueError('method must be 0 or 1.')
    return 0.


def ndcg_at_k(r, r_max, k, method=0):
    dcg_max = dcg_at_k(r_max, k, method)
    if not dcg_max:
        return 0.
    return dcg_at_k(r, k, method) / dcg_max

In [13]:
for lambda_ in tqdm(lambdas):
    top_n_size = 4
    top_n_lists_g = []
    for groups in groups_n:

        group_size = len(groups[0])
        top_n_lists = []

        for group in groups:
            rating_table = pd.DataFrame() 
            for member in group:
                prediction = svd[svd['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = prediction
                else:
                    rating_table = rating_table.set_index('tid').add(prediction.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= group_size 
            rating_table['rating'] *= lambda_
            pop = pop_normalized.copy()
            pop['rating'] *= (1 - lambda_)
            rating_table = rating_table.set_index('tid').add(pop.set_index('tid'), fill_value=0).reset_index()
    #         rating_table = rating_table[rating_table['count'] == group_size]
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            rating_table = rating_table[:top_n_size]
            top_n_list = []
            for _, row in rating_table.iterrows():
                top_n_list.append(row[0])
            top_n_lists.append(top_n_list)
        top_n_lists_g.append(top_n_lists)   
        
#     print('lambda = ' + str(lambda_))
    threshold = 0.0
    avg_nDCGs = []
    for i in range(len(groups_n)):
        groups = groups_n[i]
        top_n_lists = top_n_lists_g[i]

        nDCGs = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]
            
            for k in range(len(group)):
                truth_rating = []
                uid = group[k]
                for l in range(top_n_size):
                    tid = top_n_list[l]
                    t = test[test['uid'] == uid]
                    t = t[t['tid'] == tid]
                    if len(t) > 0:
                        truth_rating.append(t.iloc[0]['rating'])
                    else:
                        truth_rating.append(0)
                max_rating = test[test['uid']==uid].sort_values(by=['rating'],  ascending=False)['rating'].values[:top_n_size]
                nDCG = ndcg_at_k(truth_rating, max_rating, top_n_size, method=1)
                nDCGs.append(nDCG)  
                
        avg_nDCG = 0
        for nDCG in nDCGs:
            avg_nDCG += nDCG
        avg_nDCG /= len(nDCGs)
        avg_nDCGs.append(avg_nDCG)
        
    print(avg_nDCGs)
#     print('----------------------------------------')

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=11.0), HTML(value='')))

[0.03868076740523092, 0.03023877424239824, 0.03170645417763307, 0.0215434473164825, 0.032355277564591015, 0.019298732355267707, 0.0234536758032154]
----------------------------------------
[0.04205921882091408, 0.03307319798568802, 0.03320369569360559, 0.021959793296866092, 0.032355277564591015, 0.018620798741271264, 0.0234536758032154]
----------------------------------------
[0.04724063021108929, 0.03371677096728754, 0.0375093016661843, 0.022652941754618905, 0.033984787167554854, 0.015655169840220633, 0.020429379164425547]
----------------------------------------
[0.0530220315070911, 0.036630592331852806, 0.0384383061805696, 0.02167741349591283, 0.036359021678009626, 0.017095178639469497, 0.023431656597838354]
----------------------------------------
[0.06408166387512919, 0.040700312897083445, 0.0406579397619668, 0.024266814857272362, 0.036903831450131604, 0.01728932927736196, 0.023914915325069307]
----------------------------------------
[0.0695754401359781, 0.05122050706911347, 0.043532257494722754, 0.02565206683961083, 0.036947228080591046, 0.01731750140095884, 0.022462200437934076]
----------------------------------------
[0.08557453582090872, 0.0535056112875648, 0.046757268393565955, 0.028182479974278096, 0.036723695559804946, 0.017471353536146948, 0.022443876171752985]
----------------------------------------
[0.09865940463720556, 0.052171718322170685, 0.05109135240243786, 0.03161892195212037, 0.03678859390874659, 0.018299551948582828, 0.023244815643493514]
----------------------------------------
[0.10236211710553952, 0.052889763793714774, 0.05519049307582076, 0.02549931895363086, 0.034233177829462315, 0.02003026844850439, 0.010868995570159119]
----------------------------------------
[0.0988832682556222, 0.05195276378426207, 0.05354838874952115, 0.01955780738687217, 0.029687894296622674, 0.025280588104698593, 0.01800443407102123]
----------------------------------------
[0.07594984056204965, 0.035185830793337675, 0.03377351098363374, 0.020907166620389633, 0.010055717868450224, 0.028951864941909804, 0.015185187146248554]
----------------------------------------

In [195]:
alpha = 0.5
threshold = 0.0
for i in tqdm(range(len(groups_n))):
    
    groups = groups_n[i]
    top_n_lists = top_n_lists_g[i]
    
    satisfactions = []
    for j in (range(len(groups))):
        
        group = groups[j]
        top_n_list = top_n_lists[j]
        
        high_ratings_t = np.zeros(top_n_size)
        high_ratings_u = np.zeros(len(group))
        
        for k in range(top_n_size):
            for l in range(len(group)):
                uid = group[l]
                tid = top_n_list[k]
                t = test[test['uid'] == uid]
                t = t[t['tid'] == tid]
                if len(t) > 0 and t.iloc[0]['rating'] > threshold:
                    high_ratings_t[k] += 1
                    high_ratings_u[l] += 1
        
#         satisfaction_t = 0
#         for k in range(top_n_size):
#             satisfaction_t += math.log(high_ratings_t[k]+1, 10) / math.log(len(group)+1, 10)
#         satisfaction_t /= top_n_size
        
#         satisfaction_u = 0
#         for k in range(len(group)):
#             satisfaction_u += math.log(high_ratings_u[k]+1, 10) / math.log(top_n_size+1, 10)
#         satisfaction_u /= len(group)
        satisfaction_t = math.log(max(high_ratings_t)+1, 10) / math.log(len(group)+1, 10)
        satisfaction_u = math.log(min(high_ratings_u)+1, 10) / math.log(top_n_size+1, 10)
        
        satisfaction = alpha*satisfaction_t + (1-alpha)*satisfaction_u
        satisfactions.append(satisfaction)
    
    avg_satisfaction = 0
    for satisfaction in satisfactions:
        avg_satisfaction += satisfaction
    avg_satisfaction /= len(satisfactions)
    print(avg_satisfaction)

HBox(children=(FloatProgress(value=0.0, max=4.0), HTML(value='')))

0.4384689835799772
0.34093950544457624
0.3358646172870294
0.33769451038646087