In [2]:
import os 
import math
import random
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm
from numpy import count_nonzero
dir_ = '../../../data/'
group_dir_ = os.path.join(dir_, 'groups/low')

In [3]:
file_name = 'normalized_to_rating_filter_track_5_user_100.csv'
all_user = pd.read_pickle(os.path.join(dir_, file_name[:-3] + 'pkl'))
svd = pd.read_pickle(os.path.join(dir_, 'prediction_svd_top_N_' + file_name[:-3] + 'pkl'))
test = pd.read_pickle(os.path.join(dir_, 'test_' + file_name[:-3] + 'pkl'))
test.sort_values(by=['uid','tid'])

file_name = 'normalized_popularity_filter_track_5_user_100.pkl'
pop_count = pd.read_pickle(os.path.join(dir_, file_name))

num_user = len(svd['uid'].unique())
num_user

220

In [4]:
groups_n =[]
group_sizes = ['2', '3', '4', '5', '6', '7', '8']
for i in range(len(group_sizes)):
    groups = np.loadtxt(os.path.join(group_dir_, group_sizes[i] + '.csv'), delimiter=',')
    groups_n.append(groups)

In [5]:
pop_dict = {}
for i in all_user['tid'].unique():
    pop_dict[i] = len(all_user[all_user['tid']==i])/num_user

In [6]:
svd['count'] = 1
svd[:5]

   uid  tid    rating  count
0    0    3  2.544071      1
1    0    7  2.545822      1
2    0   18  2.152490      1
3    0   20  1.882396      1
4    0   31  2.410806      1

In [7]:
pop_count = pop_count.sort_values(by=['count'],  ascending=False)
pop_count[:10]

         tid  count  rating
166      166   3666  573.25
457      457   2042  162.00
6338    6338   1896  153.75
80        80   1835  412.25
1364    1364   1792  327.50
350      350   1667  359.75
7209    7209   1454  400.50
6282    6282   1397   17.75
13104  13104   1368   57.50
3761    3761   1340  354.50

In [8]:
# Linear
# size = int(len(pop_rating) // 5)
# pop_normalized = pd.DataFrame()
# for i in range(5):
#     if i == 0:
#         pop = pop_count[:size].copy()
#     elif i == 4:
#         pop = pop_count[size*4:].copy()
#     else:
#         pop = pop_count[size*i:size*(i+1)].copy()
#     pop['rating'] = (5 - i)
#     pop_normalized = pop_normalized.append(pop)
# pop_normalized = pop_normalized[['tid', 'rating']]

In [9]:
# min_max
max_rating = pop_count.iloc[0]['count']
pop_normalized = pop_count.copy()
pop_normalized = pop_normalized[['tid', 'count']]
pop_normalized['rating'] = pop_normalized['count']
pop_normalized['rating'] /= max_rating
pop_normalized['rating'] *= 5
pop_normalized[:10]

         tid  count    rating
166      166   3666  5.000000
457      457   2042  2.785052
6338    6338   1896  2.585925
80        80   1835  2.502728
1364    1364   1792  2.444081
350      350   1667  2.273595
7209    7209   1454  1.983088
6282    6282   1397  1.905346
13104  13104   1368  1.865794
3761    3761   1340  1.827605

In [10]:
lambdas = []
for i in range(11):
    lambdas.append(i/10)
lambdas

[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

In [14]:
for lambda_ in tqdm(lambdas):
    top_n_size = 4
    top_n_lists_g = []
    for groups in groups_n:

        group_size = len(groups[0])
        top_n_lists = []

        for group in groups:
            rating_table = pd.DataFrame() 
            for member in group:
                prediction = svd[svd['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = prediction
                else:
                    rating_table = rating_table.set_index('tid').add(prediction.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= group_size 
            rating_table['rating'] *= lambda_
            pop = pop_normalized.copy()
            pop['rating'] *= (1 - lambda_)
            rating_table = rating_table.set_index('tid').add(pop.set_index('tid'), fill_value=0).reset_index()
    #         rating_table = rating_table[rating_table['count'] == group_size]
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            rating_table = rating_table[:top_n_size]
            top_n_list = []
            for _, row in rating_table.iterrows():
                top_n_list.append(row[0])
            top_n_lists.append(top_n_list)
        top_n_lists_g.append(top_n_lists)   
        
    threshold = 0.0
    avg_pops = []
    for i in range(len(groups_n)):
        groups = groups_n[i]
        top_n_lists = top_n_lists_g[i]

        pops = []
        for j in (range(len(groups))):
            group = groups[j]
            top_n_list = top_n_lists[j]
            for k in range(len(group)):
                for l in range(top_n_size):
                    tid = top_n_list[l]
                    pops.append(pop_dict[tid])                    
        avg_pop = sum(pops)/len(pops)
        avg_pops.append(avg_pop)
        
    print(avg_pops)

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=11.0), HTML(value='')))

[0.48409090909091085, 0.484090909090909, 0.4840909090909089, 0.48409090909090885, 0.4840909090909088, 0.4840909090909088, 0.4840909090909088]
[0.47863636363636547, 0.4761707988980716, 0.47721291866028676, 0.4800699300699299, 0.4814772727272725, 0.4808238636363632, 0.4840909090909088]
[0.4797424242424262, 0.4759297520661159, 0.4793062200956935, 0.4780594405594404, 0.4762499999999996, 0.4710227272727267, 0.4691558441558437]
[0.48560606060606254, 0.484951790633609, 0.4795454545454543, 0.4849650349650348, 0.47715909090909053, 0.475426136363636, 0.4735389610389606]
[0.49207575757575955, 0.4870867768595045, 0.48815789473684185, 0.4911713286713286, 0.477613636363636, 0.475426136363636, 0.4735389610389606]
[0.4910757575757599, 0.4955578512396699, 0.4906698564593299, 0.49020979020978994, 0.47806818181818156, 0.4899147727272725, 0.47418831168831116]
[0.48472727272727495, 0.4751033057851242, 0.4912679425837318, 0.4897727272727269, 0.49954545454545424, 0.4818181818181814, 0.48084415584415546]
[0.47325757575757726, 0.4656680440771349, 0.47619617224880284, 0.49195804195804144, 0.49977272727272676, 0.46278409090909045, 0.483928571428571]
[0.4505151515151518, 0.4455578512396687, 0.46381578947368357, 0.4545454545454539, 0.4821590909090908, 0.44659090909090865, 0.47970779220779214]
[0.4493484848484846, 0.44163223140495766, 0.45807416267942547, 0.4452797202797196, 0.43613636363636377, 0.4140625000000001, 0.42321428571428565]
[0.3866212121212117, 0.3783746556473826, 0.38767942583732085, 0.3747377622377622, 0.4134090909090916, 0.32968749999999986, 0.3866883116883116]

In [11]:
HitNOVs = []
for lambda_ in tqdm(lambdas):
    top_n_size = 50
    top_n_lists_g = []
    for groups in groups_n:

        group_size = len(groups[0])
        top_n_lists = []

        for group in groups:
            rating_table = pd.DataFrame() 
            for member in group:
                prediction = svd[svd['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = prediction
                else:
                    rating_table = rating_table.set_index('tid').add(prediction.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= group_size 
            rating_table['rating'] *= lambda_
            pop = pop_normalized.copy()
            pop['rating'] *= (1 - lambda_)
            rating_table = rating_table.set_index('tid').add(pop.set_index('tid'), fill_value=0).reset_index()
    #         rating_table = rating_table[rating_table['count'] == group_size]
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            rating_table = rating_table[:top_n_size]
            top_n_list = []
            for _, row in rating_table.iterrows():
                top_n_list.append(row[0])
            top_n_lists.append(top_n_list)
        top_n_lists_g.append(top_n_lists)   
        
    HitNOV = []
    for i in range(len(groups_n)):
        groups = groups_n[i]
        top_n_lists = top_n_lists_g[i]
        
        nov = 0
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]
            
            for k in range(len(group)):
                for l in range(top_n_size):
                    uid = group[k]
                    tid = top_n_list[l]
                    t = test[test['uid'] == uid]
                    t = t[t['tid'] == tid]
                    if len(t) > 0:
                        nov += (1-pop_dict[tid])
        
        HitNOV.append(nov/top_n_size/(len(groups)*len(groups[0])))
    HitNOVs.append(HitNOV)
    
for HitNOV in HitNOVs:
    print(HitNOV)

HBox(children=(FloatProgress(value=0.0, max=11.0), HTML(value='')))

[0.03403818181818183, 0.024213957759412322, 0.019098086124401926, 0.020802797202797214, 0.017224242424242434, 0.018022727272727284, 0.016459415584415587]
[0.03975090909090901, 0.027322314049586793, 0.02079306220095695, 0.021548251748251764, 0.017774242424242435, 0.018673701298701308, 0.016090909090909093]
[0.04514848484848474, 0.02897245179063361, 0.02216626794258374, 0.021046153846153857, 0.017304545454545465, 0.01887987012987014, 0.01637987012987013]
[0.050024242424242304, 0.031337006427915516, 0.023534688995215314, 0.020801398601398617, 0.01794848484848486, 0.019264610389610404, 0.016733766233766236]
[0.05678363636363615, 0.033887052341597806, 0.027279904306220095, 0.021737062937062943, 0.019300000000000008, 0.020181818181818193, 0.016560064935064938]
[0.06026727272727253, 0.036876033057851254, 0.02885406698564593, 0.02321538461538462, 0.02216818181818183, 0.020722402597402607, 0.016704545454545458]
[0.06591515151515132, 0.03953994490358127, 0.03291267942583732, 0.025386013986013988, 0.023972727272727277, 0.022173701298701307, 0.01606331168831169]
[0.06665999999999982, 0.040367309458218543, 0.03481937799043062, 0.02786573426573426, 0.02650000000000001, 0.023334415584415593, 0.01753084415584415]
[0.06648484848484831, 0.04109182736455466, 0.03386602870813396, 0.02695944055944055, 0.02664242424242425, 0.025207792207792207, 0.019417207792207788]
[0.05942242424242406, 0.03790633608815431, 0.031184210526315773, 0.02657062937062936, 0.02833636363636363, 0.022602272727272728, 0.019892857142857132]
[0.050490909090908996, 0.03160606060606063, 0.02593660287081339, 0.021399999999999992, 0.02009848484848485, 0.015978896103896106, 0.017053571428571425]

In [ ]:
tid_pd = pd.DataFrame(data={'tid': all_user['tid'].unique()})
tid_pd = tid_pd.sort_values(by=['tid']).reset_index()
long_tail_list = tid_pd['tid'].isin(long_tail)
long_tail_list = list(long_tail_list)
long_tail_list.count(True)

In [13]:
diversities = []
novelties = []
for lambda_ in tqdm(lambdas):
    top_n_size = 50
    top_n_lists_g = []
    for groups in groups_n:

        group_size = len(groups[0])
        top_n_lists = []

        for group in groups:
            rating_table = pd.DataFrame() 
            for member in group:
                prediction = svd[svd['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = prediction
                else:
                    rating_table = rating_table.set_index('tid').add(prediction.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= group_size 
            rating_table['rating'] *= lambda_
            pop = pop_normalized.copy()
            pop['rating'] *= (1 - lambda_)
            rating_table = rating_table.set_index('tid').add(pop.set_index('tid'), fill_value=0).reset_index()
    #         rating_table = rating_table[rating_table['count'] == group_size]
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            rating_table = rating_table[:top_n_size]
            top_n_list = []
            for _, row in rating_table.iterrows():
                top_n_list.append(row[0])
            top_n_lists.append(top_n_list)
        top_n_lists_g.append(top_n_lists)   
        
    diversity = []
    novelty = []
    for i in range(len(groups_n)):
        groups = groups_n[i]
        top_n_lists = top_n_lists_g[i]

        
        hits = np.zeros(len(all_user['tid'].unique()), dtype=bool)
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]
            
            for k in range(len(group)):
                for l in range(top_n_size):
                    uid = group[k]
                    tid = top_n_list[l]
                    t = test[test['uid'] == uid]
                    t = t[t['tid'] == tid]
                    if len(t) > 0:
                        hits[int(tid)] = True
        
        diversity.append(list(hits).count(True)/len(all_user['tid'].unique()))
#         novelty.append(list(hits&long_tail_list).count(True)/len(df['tid'].unique()))
    diversities.append(diversity)
#     novelties.append(novelty)
    
for diversity in diversities:
    print(diversity)
print()
for novelty in novelties:
    print(novelty)

HBox(children=(FloatProgress(value=0.0, max=11.0), HTML(value='')))

[0.0008732194509632703, 0.000855027379068202, 0.0007458749476977933, 0.0007822590914879295, 0.0006731066601175208, 0.0006912987320125889, 0.0006549145882224527]
[0.0011824846731794284, 0.0010369480980188834, 0.0008914115228583384, 0.0008732194509632703, 0.0007458749476977933, 0.0007640670195928614, 0.000709490803907657]
[0.0016554785424511998, 0.0012188688169695646, 0.0010005639542287471, 0.0008914115228583384, 0.0007640670195928614, 0.0007822590914879295, 0.0007276828758027252]
[0.0021648565555131075, 0.0014371736797103823, 0.0011642926012843603, 0.0009277956666484746, 0.0007822590914879295, 0.0008368353071731339, 0.0007640670195928614]
[0.0027470028561552874, 0.0017282468300314723, 0.001418981607815314, 0.0010369480980188834, 0.0009096035947534065, 0.0009277956666484746, 0.0007640670195928614]
[0.003274572941112263, 0.0020193199803525625, 0.001564518182975859, 0.0011461005293892921, 0.0010915243137040878, 0.0010187560261238151, 0.0008368353071731339]
[0.004020447888810057, 0.0023467772744637885, 0.0018919754770870855, 0.0013825974640251778, 0.0012006767450744966, 0.0011642926012843603, 0.0008368353071731339]
[0.004511633829976896, 0.002546890065309538, 0.002128472411722971, 0.0015827102548709273, 0.0013825974640251778, 0.0013098291764449053, 0.0009459877385435427]
[0.005075588058724008, 0.002928923575105969, 0.0021466644836180392, 0.0016190943986610635, 0.0014735578235005185, 0.0014553657516054503, 0.0010733322418090196]
[0.005293892921464826, 0.0030198839345813096, 0.002128472411722971, 0.0018010151176117448, 0.001691862686241336, 0.0014553657516054503, 0.0011097163855991559]
[0.005621350215576052, 0.0028561552875256964, 0.0020011279084574942, 0.0015099419672906548, 0.001273445032654769, 0.0010551401699139516, 0.0009096035947534065]