In [75]:
import os 
import math
import random
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm
from scipy.stats import kendalltau
from scipy.stats import rankdata
from sklearn.model_selection import train_test_split
from numpy import count_nonzero

dir_ = '../data/'
group_dir_ = '../data/groups/low'

In [76]:
file_name = 'normalized_to_rating_filter_track_5_user_100.csv'
svd = pd.read_pickle(os.path.join(dir_, 'prediction_svd_top_N_' + file_name[:-3] + 'pkl'))
test = pd.read_pickle(os.path.join(dir_, 'test_' + file_name[:-3] + 'pkl'))
test.sort_values(by=['uid','tid'])

file_name = 'normalized_popularity_filter_track_5_user_100.csv'
pop_count = pd.read_pickle(os.path.join(dir_, 'prediction_popularity_count_top_N_' + file_name[:-3] + 'pkl'))
pop_rating = pd.read_pickle(os.path.join(dir_, 'prediction_popularity_rating_top_N_' + file_name[:-3] + 'pkl'))

num_user = len(svd['uid'].unique())
num_user

220

In [77]:
groups_n_train = []
groups_n_test = []
group_sizes = ['2', '3', '4', '5']
for i in range(len(group_sizes)):
    groups = np.loadtxt(os.path.join(group_dir_, 'group_' + group_sizes[i] + '.csv'), delimiter=',')
    num_groups = len(groups)
    groups_part1 =  groups[:int(num_groups*0.2)]
    groups_part2 =  groups[int(num_groups*0.2):int(num_groups*0.4)]
    groups_part3 =  groups[int(num_groups*0.4):int(num_groups*0.6)]
    groups_part4 =  groups[int(num_groups*0.6):int(num_groups*0.8)]
    groups_part5 =  groups[int(num_groups*0.8):]
    groups_train = np.concatenate((groups_part1, groups_part3, groups_part4, groups_part5))
    groups_test = groups_part2
    print(len(groups_train), len(groups_test))
    groups_n_train.append(groups_train)
    groups_n_test.append(groups_test)
    if i == 3:
        print(groups_part1, '\n\n', groups_part2, '\n\n', groups_part3, '\n\n', groups_part4, '\n\n', groups_part5, '\n\n')
        print(groups_train,'\n\n', groups_test)

67 17
28 7
17 4
13 3
[[110.  27.  15. 154. 197.]
 [  6.  36.  53. 114. 153.]
 [174. 146. 121.  18.  34.]]

 [[ 68.  25. 175. 128. 152.]
 [165.  51. 129.   1. 122.]
 [ 60.  54.  83.  29. 216.]]

 [[198. 201. 186. 168.  84.]
 [ 10. 139.  86. 131. 133.]
 [214.  28. 200.  69. 118.]]

 [[ 75. 181. 217.  70.  85.]
 [185.   9.  67. 149. 162.]
 [144. 112. 184. 136. 206.]]

 [[190.  21. 204.   5.  94.]
 [205.  76.  26.  42. 117.]
 [ 30.  92.  87. 159. 218.]
 [109.  65. 208. 145.  35.]]


[[110.  27.  15. 154. 197.]
 [  6.  36.  53. 114. 153.]
 [174. 146. 121.  18.  34.]
 [198. 201. 186. 168.  84.]
 [ 10. 139.  86. 131. 133.]
 [214.  28. 200.  69. 118.]
 [ 75. 181. 217.  70.  85.]
 [185.   9.  67. 149. 162.]
 [144. 112. 184. 136. 206.]
 [190.  21. 204.   5.  94.]
 [205.  76.  26.  42. 117.]
 [ 30.  92.  87. 159. 218.]
 [109.  65. 208. 145.  35.]]

 [[ 68.  25. 175. 128. 152.]
 [165.  51. 129.   1. 122.]
 [ 60.  54.  83.  29. 216.]]

In [78]:
for i in groups_n_train:
    print(len(i[0]))

2
3
4
5

In [79]:
svd['count'] = 1
svd

            uid      tid    rating  count
0           0.0      0.0  2.493650      1
1           0.0      6.0  2.333071      1
2           0.0      8.0  2.713340      1
3           0.0      9.0  1.949588      1
4           0.0     12.0  2.477737      1
...         ...      ...       ...    ...
11741994  219.0  54964.0  1.816855      1
11741995  219.0  54965.0  2.315346      1
11741996  219.0  54966.0  1.954432      1
11741997  219.0  54967.0  2.071366      1
11741998  219.0  54968.0  2.377146      1

[11741999 rows x 4 columns]

In [80]:
pop_count = pop_count.sort_values(by=['count'],  ascending=False)
pop_count

         tid  count  rating
166      166   1882  333.50
6310    6338   1589   92.25
17316  17377   1555   43.50
6254    6282   1396   17.50
13055  13104   1340   33.50
...      ...    ...     ...
25819  25941      1    0.25
43440  43743      1    0.25
54130  54607      1    0.25
27486  27620      1    0.25
25232  25344      1    0.25

[54480 rows x 3 columns]

In [81]:
# min_max
max_rating = pop_count.iloc[0]['count']
pop_normalized = pop_count.copy()
pop_normalized = pop_normalized[['tid', 'count']]
pop_normalized['rating'] = pop_normalized['count']
pop_normalized['rating'] /= max_rating
pop_normalized['rating'] *= 5
pop_normalized

         tid  count    rating
166      166   1882  5.000000
6310    6338   1589  4.221573
17316  17377   1555  4.131243
6254    6282   1396  3.708820
13055  13104   1340  3.560043
...      ...    ...       ...
25819  25941      1  0.002657
43440  43743      1  0.002657
54130  54607      1  0.002657
27486  27620      1  0.002657
25232  25344      1  0.002657

[54480 rows x 3 columns]

In [82]:
def dcg_at_k(r, k, method=0):
    r = np.asfarray(r)[:k]
    for i in range(len(r)):
        r[i] = 2**r[i] -1
    
    if r.size:
        if method == 0:
            return r[0] + np.sum(r[1:] / np.log2(np.arange(2, r.size + 1)))
        elif method == 1:
            return np.sum(r / np.log2(np.arange(2, r.size + 2)))
        else:
            raise ValueError('method must be 0 or 1.')
    return 0.


def ndcg_at_k(r, k, method=0):
    dcg_max = dcg_at_k(sorted(r, reverse=True), k, method)
    if not dcg_max:
        return 0.
    return dcg_at_k(r, k, method) / dcg_max

In [83]:
lambdas = []
for i in range(11):
    lambdas.append(i/10)
lambdas

[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

In [84]:
top_n_size = 20
optimal_lambdas = []
results_precision = []
results_satisfaction = []
results_tau = []
results_DCG = []
results_nDCG = []
for i in range(len(groups_n_train)):
    results_tau.append([])
    results_nDCG.append([])
    results_precision.append([])
    results_DCG.append([])
    results_satisfaction.append([])
truth_rank = []
for i in range(top_n_size):
    truth_rank.append(i+1)

In [85]:
for lambda_ in tqdm(lambdas):
    top_n_lists_g = []
    for groups in groups_n_train:

        group_size = len(groups[0])
        top_n_lists = []

        for group in groups:
            rating_table = pd.DataFrame() 
            for member in group:
                prediction = svd[svd['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = prediction
                else:
                    rating_table = rating_table.set_index('tid').add(prediction.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= group_size 
            rating_table['rating'] *= lambda_
            pop = pop_normalized.copy()
            pop['rating'] *= (1 - lambda_)
            rating_table = rating_table.set_index('tid').add(pop.set_index('tid'), fill_value=0).reset_index()
    #         rating_table = rating_table[rating_table['count'] == group_size]
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            rating_table = rating_table[:top_n_size]
            top_n_list = []
            for _, row in rating_table.iterrows():
                top_n_list.append(row[0])
            top_n_lists.append(top_n_list)
        top_n_lists_g.append(top_n_lists)   
        
    threshold = 0.0
    for i in range(len(groups_n_train)):
        groups = groups_n_train[i]
        top_n_lists = top_n_lists_g[i]

        precisions = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            high_rating = 0

            for k in range(top_n_size):
                for l in range(len(group)):
                    uid = group[l]
                    tid = top_n_list[k]
                    t = test[test['uid'] == uid]
                    t = t[t['tid'] == tid]
                    if len(t) > 0 and t.iloc[0]['rating'] > threshold:
                        high_rating += 1
                        break

            precision = high_rating / top_n_size
            precisions.append(precision)
        
        satisfactions = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            high_ratings_t = np.zeros(top_n_size)
            high_ratings_u = np.zeros(len(group))

            for k in range(top_n_size):
                for l in range(len(group)):
                    uid = group[l]
                    tid = top_n_list[k]
                    t = test[test['uid'] == uid]
                    t = t[t['tid'] == tid]
                    if len(t) > 0 and t.iloc[0]['rating'] > threshold:
                        high_ratings_t[k] += 1
                        high_ratings_u[l] += 1

            satisfaction_t = 0
            for k in range(top_n_size):
                satisfaction_t += math.log(high_ratings_t[k]+1, 10) / math.log(len(group)+1, 10)
            satisfaction_t /= top_n_size

            satisfaction_u = 0
            for k in range(len(group)):
                satisfaction_u += math.log(high_ratings_u[k]+1, 10) / math.log(top_n_size+1, 10)
            satisfaction_u /= len(group)

            satisfaction = 0.5*satisfaction_t + (1-0.5)*satisfaction_u
            satisfactions.append(satisfaction)
        
        taus = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            rating_table = pd.DataFrame() 
            for member in group:
                average = test[test['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = average
                else:
                    rating_table = rating_table.set_index('tid').add(average.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= len(group) 
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            rating_table = rating_table[:top_n_size]
            
            ground_truth = []
            for _, row in rating_table.iterrows():
                ground_truth.append(row[0])
            
            pred_rank = []
            for k in top_n_list:
                if k in ground_truth:
                    pred_rank.append(ground_truth.index(k)+1)
                else:
                    pred_rank.append(top_n_size+1)
            tau, p_value = kendalltau(truth_rank, pred_rank)
            taus.append(tau)

        nDCGs = []
        DCGs = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            rating_table = pd.DataFrame() 
            for member in group:
                average = test[test['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = average
                else:
                    rating_table = rating_table.set_index('tid').add(average.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= len(group) 
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            
            truth_rating = []
            for k in top_n_list:
                r = rating_table[rating_table['tid']==k]
                if len(r) > 0:
                    truth_rating.append(r.iloc[0]['rating'])
                else:
                    truth_rating.append(0)
            nDCG = ndcg_at_k(truth_rating, top_n_size, method=1)
            DCG = dcg_at_k(truth_rating, top_n_size, method=1)
            nDCGs.append(nDCG)
            DCGs.append(DCG)
            

    
        avg_satisfaction = 0
        for satisfaction in satisfactions:
            avg_satisfaction += satisfaction
        avg_satisfaction /= len(satisfactions)
    
        avg_precision = 0
        for precision in precisions:
            avg_precision += precision
        avg_precision /= len(precisions)
        
        n_tau = 0
        avg_tau = 0
        for tau in taus:
            if not np.isnan(tau):
                avg_tau += tau
                n_tau += 1
        avg_tau /= n_tau
        
        avg_nDCG = 0
        for nDCG in nDCGs:
            avg_nDCG += nDCG
        avg_nDCG /= len(nDCGs)      
        
        avg_DCG = 0
        for DCG in DCGs:
            avg_DCG += DCG
        avg_DCG /= len(DCGs)
        
        results_precision[i].append(avg_precision)
        results_satisfaction[i].append(avg_satisfaction)
        results_tau[i].append(avg_tau)
        results_nDCG[i].append(avg_nDCG)
        results_DCG[i].append(avg_DCG)

HBox(children=(FloatProgress(value=0.0, max=11.0), HTML(value='')))

In [86]:
ranks_precision = []
ranks_tau = []
ranks_DCG = []
ranks_nDCG = []
ranks_satisfaction = []

In [87]:
for i in results_precision:
    ranks_precision.append(rankdata(i))
for i in results_tau:
    ranks_tau.append(rankdata(i))
for i in results_DCG:
    ranks_DCG.append(rankdata(i))
for i in results_nDCG:
    ranks_nDCG.append(rankdata(i))
for i in results_satisfaction:
    ranks_satisfaction.append(rankdata(i))

In [88]:
for i in results_precision:
    print(i)
print()
for i in results_satisfaction:
    print(i)

[0.26119402985074625, 0.26044776119402985, 0.26492537313432835, 0.2805970149253731, 0.3134328358208956, 0.3410447761194029, 0.3723880597014925, 0.3992537313432836, 0.38955223880597, 0.3253731343283582, 0.24402985074626862]
[0.3124999999999999, 0.3107142857142856, 0.30535714285714277, 0.3124999999999999, 0.32857142857142846, 0.35000000000000003, 0.37500000000000006, 0.40178571428571436, 0.4089285714285715, 0.40357142857142864, 0.29821428571428565]
[0.35000000000000003, 0.3470588235294118, 0.34411764705882353, 0.34705882352941175, 0.36176470588235293, 0.40882352941176475, 0.42941176470588227, 0.46470588235294114, 0.4558823529411765, 0.45294117647058824, 0.35588235294117654]
[0.33461538461538465, 0.33461538461538465, 0.3269230769230769, 0.3307692307692308, 0.34230769230769226, 0.34615384615384615, 0.37692307692307686, 0.4076923076923077, 0.4230769230769231, 0.38461538461538464, 0.29230769230769227]

[0.28171864636232236, 0.280841935911901, 0.28290077504424865, 0.29280921602399446, 0.31455289877079134, 0.33193772972992996, 0.3493780231323797, 0.3648379500184814, 0.3548689848690664, 0.3062146003062579, 0.23183687160447625]
[0.26259707052632336, 0.26171437142259996, 0.25710463137324874, 0.26032911161044275, 0.2696685792240462, 0.28148396321289704, 0.29370225830023244, 0.30630330570736686, 0.3064837008732835, 0.29570215789684023, 0.2155736408884124]
[0.23727472419263324, 0.23610245389086693, 0.23505877642795622, 0.23715421541749288, 0.24053557015353752, 0.2671180103646083, 0.2801788606857114, 0.29478189167928487, 0.27923084688208155, 0.26751711846362386, 0.20764784024007832]
[0.22096200132632932, 0.22096200132632932, 0.21802038759574452, 0.21978878574825386, 0.2183745057939917, 0.2187289755165659, 0.2374389279337081, 0.24782883480967552, 0.2515805377262804, 0.2338941609385764, 0.18392557997276265]

In [89]:
optimized_lambdas = []
for i in range(len(groups_n_test)):
    print(ranks_satisfaction[i])
#     print('--------------------------------------------------')
    print(ranks_precision[i])
#     print(ranks_tau[i])
#     print(ranks_DCG[i])
#     print(ranks_nDCG[i])
#     print(ranks_precision[i] + ranks_tau[i] + ranks_DCG[i] + ranks_nDCG[i])
#     ranks = (ranks_precision[i] + ranks_tau[i] + ranks_DCG[i] + ranks_nDCG[i]).tolist()
#     print(ranks.index(max(ranks)))
    print('--------------------------------------------------')
#     optimized_lambdas.append()

[ 3.  2.  4.  5.  7.  8.  9. 11. 10.  6.  1.]
[ 3.  2.  4.  5.  6.  8.  9. 11. 10.  7.  1.]
--------------------------------------------------
[ 5.  4.  2.  3.  6.  7.  8. 10. 11.  9.  1.]
[ 4.5  3.   2.   4.5  6.   7.   8.   9.  11.  10.   1. ]
--------------------------------------------------
[ 5.  3.  2.  4.  6.  7. 10. 11.  9.  8.  1.]
[ 4.  3.  1.  2.  6.  7.  8. 11. 10.  9.  5.]
--------------------------------------------------
[ 6.5  6.5  2.   5.   3.   4.   9.  10.  11.   8.   1. ]
[ 4.5  4.5  2.   3.   6.   7.   8.  10.  11.   9.   1. ]
--------------------------------------------------

In [90]:
final_results_precision = []
final_results_tau = []
final_results_DCG = []
final_results_nDCG = []
for i in range(len(groups_n_test)):
    final_results_tau.append([])
    final_results_nDCG.append([])
    final_results_precision.append([])
    final_results_DCG.append([])
truth_rank = []
for i in range(top_n_size):
    truth_rank.append(i+1)

In [91]:
print(lambdas)

[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

In [92]:
for lambda_ in tqdm(lambdas):
    top_n_lists_g = []
    for groups in groups_n_test:

        group_size = len(groups[0])
        top_n_lists = []

        for group in groups:
            rating_table = pd.DataFrame() 
            for member in group:
                prediction = svd[svd['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = prediction
                else:
                    rating_table = rating_table.set_index('tid').add(prediction.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= group_size 
            rating_table['rating'] *= lambda_
            pop = pop_normalized.copy()
            pop['rating'] *= (1 - lambda_)
            rating_table = rating_table.set_index('tid').add(pop.set_index('tid'), fill_value=0).reset_index()
    #         rating_table = rating_table[rating_table['count'] == group_size]
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            rating_table = rating_table[:top_n_size]
            top_n_list = []
            for _, row in rating_table.iterrows():
                top_n_list.append(row[0])
            top_n_lists.append(top_n_list)
        top_n_lists_g.append(top_n_lists)   
        
    threshold = 0.0
    for i in range(len(groups_n_test)):
        groups = groups_n_test[i]
        top_n_lists = top_n_lists_g[i]

        precisions = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            high_rating = 0

            for k in range(top_n_size):
                for l in range(len(group)):
                    uid = group[l]
                    tid = top_n_list[k]
                    t = test[test['uid'] == uid]
                    t = t[t['tid'] == tid]
                    if len(t) > 0 and t.iloc[0]['rating'] > threshold:
                        high_rating += 1
                        break

            precision = high_rating / top_n_size
            precisions.append(precision)
        
        taus = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            rating_table = pd.DataFrame() 
            for member in group:
                average = test[test['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = average
                else:
                    rating_table = rating_table.set_index('tid').add(average.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= len(group) 
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            rating_table = rating_table[:top_n_size]
            
            ground_truth = []
            for _, row in rating_table.iterrows():
                ground_truth.append(row[0])
            
            pred_rank = []
            for k in top_n_list:
                if k in ground_truth:
                    pred_rank.append(ground_truth.index(k)+1)
                else:
                    pred_rank.append(top_n_size+1)
            tau, p_value = kendalltau(truth_rank, pred_rank)
            taus.append(tau)

        nDCGs = []
        DCGs = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            rating_table = pd.DataFrame() 
            for member in group:
                average = test[test['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = average
                else:
                    rating_table = rating_table.set_index('tid').add(average.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= len(group) 
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            
            truth_rating = []
            for k in top_n_list:
                r = rating_table[rating_table['tid']==k]
                if len(r) > 0:
                    truth_rating.append(r.iloc[0]['rating'])
                else:
                    truth_rating.append(0)
            nDCG = ndcg_at_k(truth_rating, top_n_size, method=1)
            DCG = dcg_at_k(truth_rating, top_n_size, method=1)
            nDCGs.append(nDCG)
            DCGs.append(DCG)
    
        avg_precision = 0
        for precision in precisions:
            avg_precision += precision
        avg_precision /= len(precisions)
        
        n_tau = 0
        avg_tau = 0
        for tau in taus:
            if not np.isnan(tau):
                avg_tau += tau
                n_tau += 1
        if n_tau != 0:
            avg_tau /= n_tau
        else:
            avg_tau = -200 #NA
        
        avg_nDCG = 0
        for nDCG in nDCGs:
            avg_nDCG += nDCG
        avg_nDCG /= len(nDCGs)      
        
        avg_DCG = 0
        for DCG in DCGs:
            avg_DCG += DCG
        avg_DCG /= len(DCGs)
        
        final_results_precision[i].append(avg_precision)
        final_results_tau[i].append(avg_tau)
        final_results_nDCG[i].append(avg_nDCG)
        final_results_DCG[i].append(avg_DCG)

HBox(children=(FloatProgress(value=0.0, max=11.0), HTML(value='')))

In [93]:
for i in final_results_precision:
    print(i)
print()
for i in final_results_tau:
    print(i)
print()
for i in final_results_DCG:
    print(i)    
print()
for i in final_results_nDCG:
    print(i)

[0.25588235294117645, 0.25588235294117645, 0.2676470588235294, 0.3058823529411765, 0.33529411764705885, 0.36470588235294116, 0.42058823529411765, 0.43529411764705883, 0.42352941176470593, 0.39705882352941174, 0.32058823529411773]
[0.25, 0.25, 0.2571428571428571, 0.2857142857142857, 0.3142857142857142, 0.35000000000000003, 0.37142857142857144, 0.41428571428571426, 0.45, 0.42142857142857143, 0.3785714285714286]
[0.375, 0.375, 0.375, 0.3875, 0.4125, 0.48750000000000004, 0.525, 0.5375, 0.5375, 0.55, 0.41250000000000003]
[0.4166666666666667, 0.4166666666666667, 0.39999999999999997, 0.39999999999999997, 0.39999999999999997, 0.3833333333333333, 0.39999999999999997, 0.3833333333333333, 0.4666666666666666, 0.48333333333333334, 0.2333333333333333]

[0.07161403496405558, 0.11097426131996693, 0.14628331106713433, 0.09502065581504572, 0.155403366100907, 0.16279383003915912, 0.18472379568416736, 0.2445591527607117, 0.27977974212078216, 0.21015113697460192, 0.27030622801672133]
[0.2952715779654191, 0.2952715779654191, 0.2952715779654191, 0.3071983340486365, 0.31912509013185386, 0.10734080474895663, 0.04305757863867088, 0.10131006185229892, -0.03419687648204618, 0.05972360022281903, -0.09500985953544513]
[-0.04287776246218958, -0.013339020980206095, -0.000141920422296928, -0.019018962173163567, 0.015326409664799692, 0.07352529366919774, 0.1264782478378316, 0.174020720233704, 0.3411225237692433, 0.37070976082366053, 0.3162277660168379]
[0.3162277660168379, 0.3162277660168379, 0.3162277660168379, 0.3162277660168379, 0.10540925533894596, 0.12760067751556617, 0.13869638860387626, 0.14979209969218635, 0.14979209969218635, 0.0, 0.3162277660168379]

[8.55003628983823, 8.6066632099596, 8.788530242021887, 9.46103121823548, 9.943075987632726, 10.463703547212742, 11.451706012219589, 12.136733029110687, 13.471136351874705, 11.101669866499268, 6.762645201044108]
[4.241946397572607, 4.258271077854014, 4.353045417881475, 4.500484988250869, 4.712339460197605, 5.166231290488691, 5.297476746673769, 5.899241495292007, 6.244804988414637, 6.105900557975021, 3.972607252123921]
[5.07690234846673, 5.102058543873487, 5.1244621370407994, 5.246371270788872, 5.34595626792805, 5.7321616176368115, 6.05328742092473, 6.642015496138883, 6.448302461262434, 6.3885453308299045, 2.285462100728297]
[3.67601448679155, 3.6751877563193744, 3.6238343669149398, 3.631139351166802, 3.716815572746777, 3.703551150707814, 3.7365005901623642, 3.7149509313753755, 3.567663930566679, 3.3901087427446064, 2.5436827708390006]

[0.6241791256465072, 0.6287351199883136, 0.6375686421746254, 0.6248341617285624, 0.6213230476061421, 0.6342721454129111, 0.6511317209334756, 0.6785312038093757, 0.7521695446877008, 0.682981392368965, 0.5665508768697429]
[0.6396287296156047, 0.6431737266696234, 0.6515708842432867, 0.6694269711631128, 0.6830795628752246, 0.6922339337879174, 0.6155419175594378, 0.6230060852141464, 0.6804222088849624, 0.7193262292738222, 0.5962193298617248]
[0.6991741748411411, 0.70310950417148, 0.7071428283298388, 0.7135247210675911, 0.7269301968397485, 0.7311768648148629, 0.7424138104998634, 0.804426714739043, 0.8389662979992449, 0.7665286444197774, 0.5517187605972144]
[0.7802574957958238, 0.7802560982289943, 0.7847957304050869, 0.7870845092552798, 0.7470089999368362, 0.7560243686837257, 0.7550124949293792, 0.7593919746644842, 0.6713102036015886, 0.6861948040456421, 0.6847323183559899]